# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the docker container image version you desire here
      - image: circleci/node:8.14.0-jessie

    working_directory: ~/node-blog # Directory where steps will run

    steps:
      - checkout # Special step to check out source code to working directory

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      # Download and cache dependencies
      - restore_cache: # Special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: install-npm-packages
          command: |
            npm install

      - save_cache: # Special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Setup Environment Variables
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=ndoe-blog' >> $BASH_ENV

      - run: # Linitng
          name: Linting
          command: ./node_modules/.bin/eslint app.js

      - setup_remote_docker:
          docker_layer_caching: true

      - run: # Build image
          name: Build Docker image
          command: |
            docker build -t yufuluo/$IMAGE_NAME:$TAG .

      - run: # Run tests in the docker image that we just built
          name: test
          command: |
            docker run --name $IMAGE_NAME -dit yufuluo/$IMAGE_NAME:$TAG
            docker exec $IMAGE_NAME npm test test/test.js
          environment:
            NODE_ENV: test

      - run: # Push image
          name: Push Docker image
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push yufuluo/$IMAGE_NAME:$TAG
